---
- name: Setup and configure a web server  #will show this message while play
  hosts: webservers
  become: yes  # This ensures that tasks are run with elevated privileges (e.g., sudo)
  vars:                                 # can add it to seperate variable.yml as well
    web_user: webadmin
    web_group: webadmin
    config_file_src: ./files/nginx.conf
    config_file_dest: /etc/nginx/nginx.conf
    welcome_page: /usr/share/nginx/html/index.html
    service_name: 
      - nginx
      - httpd
  tasks:
    - name: Create a group for the web server   #will show this message while play
      group:
        name: "{{ web_group }}"
        state: present

    - name: Create a user for the web server
      user:
        name: "{{ web_user }}"
        group: "{{ web_group }}"
        state: present
        shell: /bin/bash

    - name: Install necessary packages
      yum:
        name: nginx
        state: present
      notify:
        - Restart nginx

    - name: Copy the nginx configuration file to the server
      copy:
        src: "{{ config_file_src }}"
        dest: "{{ config_file_dest }}"
        owner: root
        group: root
        mode: '0644'
      notify:
        - Restart nginx

    - name: Ensure a welcome message is in the default webpage
      lineinfile:
        path: "{{ welcome_page }}"
        line: "Welcome to the Web Server!"
        state: present

    - name: Ensure nginx is started and enabled at boot
      service:
        name: "{{ service_name }}"
        state: started
        enabled: yes

    - name: Fetch the nginx access log to the local machine
      fetch:
        src: /var/log/nginx/access.log
        dest: ./logs/nginx_access.log
        flat: yes

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted

- name: Setup and configure a test server as well
  hosts: testservers
  become: yes
  tasks:
    - import_tasks: web_config.yml              # you can just list of tasks from other yml files
    - import_tasks: start_servers.yml           #only for reference

- name: setting up for dev server as well
  hosts: devservers
  become: yes
  tasks:
    - import_tasks: web_config.yml
    - import_tasks: start_servers.yml         #only for reference

- name: Setting up for web server as well
  vars_files:
    - /path/to/variables.yml                # you can give path for variables
  hosts: webservers
  become: yes
  tasks:
    - import_tasks: web_config.yml
    - import_tasks: start_servers.yml

#creating simple loop:
- name: creating a simple loop
  hosts: devservers
  tasks:
    - copy:
        src: "{{ item }}"
        dest: /backup
      with_items:
        - /etc/passwd
        - /etc/group
        - /etc/shadow
